import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";

// @ts-expect-error Generated by `pnpm cf:build`; absent before the first build.
import openNextWorker from "./.open-next/worker.js";

export interface RuntimeHealthParams {
  requestId: string;
}

export interface RuntimeHealthResult {
  appEnv: CloudflareEnv["APP_ENV"];
  ok: true;
  requestId: string;
}

export class RuntimeHealthWorkflow extends WorkflowEntrypoint<CloudflareEnv, RuntimeHealthParams> {
  override async run(
    event: WorkflowEvent<RuntimeHealthParams>,
    step: WorkflowStep,
  ): Promise<RuntimeHealthResult> {
    return step.do("confirm-runtime", async () => ({
      appEnv: this.env.APP_ENV,
      ok: true as const,
      requestId: event.payload.requestId,
    }));
  }
}

export default {
  fetch: openNextWorker.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
