import { WorkflowEntrypoint, type WorkflowEvent, type WorkflowStep } from "cloudflare:workers";

// @ts-expect-error Generated by `pnpm cf:build`; absent before the first build.
import openNextWorker from "./.open-next/worker.js";

export interface RuntimeHealthParams {
  requestId: string;
}

export interface RuntimeHealthResult {
  appEnv: CloudflareEnv["APP_ENV"];
  ok: true;
  requestId: string;
}

export class RuntimeHealthWorkflow extends WorkflowEntrypoint<CloudflareEnv, RuntimeHealthParams> {
  override async run(
    event: WorkflowEvent<RuntimeHealthParams>,
    step: WorkflowStep,
  ): Promise<RuntimeHealthResult> {
    return step.do("confirm-runtime", async () => ({
      appEnv: this.env.APP_ENV,
      ok: true as const,
      requestId: event.payload.requestId,
    }));
  }
}

const NO_STORE = {
  "Cache-Control": "no-store",
  "X-Content-Type-Options": "nosniff",
};

function isWaitlistRequest(request: Request): boolean {
  if (request.method !== "POST") {
    return false;
  }

  try {
    const url = new URL(request.url);
    return url.pathname === "/api/waitlist/request";
  } catch {
    return false;
  }
}

export default {
  async fetch(request, env, ctx) {
    if (env.APP_ENV === "production" && isWaitlistRequest(request)) {
      const ip = request.headers.get("CF-Connecting-IP");
      if (!ip) {
        return new Response(JSON.stringify({ kind: "temporary_failure" }), {
          status: 503,
          headers: {
            ...NO_STORE,
            "Content-Type": "application/json",
          },
        });
      }

      const limiter = (
        env as CloudflareEnv & {
          WAITLIST_RATE_LIMITER?: { limit: (input: { key: string }) => Promise<{ success: boolean }> };
        }
      ).WAITLIST_RATE_LIMITER;

      if (limiter) {
        const { success } = await limiter.limit({ key: ip });
        if (!success) {
          return new Response(JSON.stringify({ kind: "temporary_failure" }), {
            status: 429,
            headers: {
              ...NO_STORE,
              "Content-Type": "application/json",
            },
          });
        }
      }
    }

    return openNextWorker.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
