import "server-only";

import { parseModelEnvironment, type ModelEnvironment } from "@/config/model/schema";

/**
 * Reads model gateway credentials and route settings from server-side bindings only.
 *
 * Keep this accessor out of client modules: the returned object includes provider API keys.
 */
export function getServerModelEnvironment(): ModelEnvironment {
  return parseModelEnvironment({
    ANTHROPIC_API_KEY: process.env.ANTHROPIC_API_KEY,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    GEMINI_API_KEY: process.env.GEMINI_API_KEY,
    MODEL_PRIMARY_PROVIDER: process.env.MODEL_PRIMARY_PROVIDER,
    MODEL_PRIMARY_MODEL: process.env.MODEL_PRIMARY_MODEL,
    MODEL_PRIMARY_INPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_PRIMARY_INPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_PRIMARY_OUTPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_PRIMARY_OUTPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_FALLBACK_PROVIDER: process.env.MODEL_FALLBACK_PROVIDER,
    MODEL_FALLBACK_MODEL: process.env.MODEL_FALLBACK_MODEL,
    MODEL_FALLBACK_INPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_FALLBACK_INPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_FALLBACK_OUTPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_FALLBACK_OUTPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_REVIEWER_PROVIDER: process.env.MODEL_REVIEWER_PROVIDER,
    MODEL_REVIEWER_MODEL: process.env.MODEL_REVIEWER_MODEL,
    MODEL_REVIEWER_INPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_REVIEWER_INPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_REVIEWER_OUTPUT_COST_MICROS_PER_MILLION_TOKENS:
      process.env.MODEL_REVIEWER_OUTPUT_COST_MICROS_PER_MILLION_TOKENS,
    MODEL_TOTAL_DEADLINE_MS: process.env.MODEL_TOTAL_DEADLINE_MS,
    MODEL_ATTEMPT_TIMEOUT_MS: process.env.MODEL_ATTEMPT_TIMEOUT_MS,
    MODEL_MAX_OUTPUT_TOKENS: process.env.MODEL_MAX_OUTPUT_TOKENS,
  });
}
